runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /
  static_files: yes_virginia.html
  upload: yes_virginia.html

- url: /logos.html
  static_files: logos.html
  upload: logos.html

- url: /.*
  script: main.py
